#!/bin/bash
REMOTE=$(git config --get remote.origin.url)
if [[ $REMOTE =~ "github.infra.hana.ondemand.com" || $REMOTE =~ "/SAP/" ]]; then
  git config --local  user.email "murali.suresh@sap.com"
else
  git config --local  user.email "muralisc@gmail.com"
  git config --local  credential.username 'i330301'
fi

