#!/bin/bash
if [[ $(git config --get remote.origin.url) =~ "github.infra.hana.ondemand.com" ]]; then
  git config --local  user.email "murali.suresh@sap.com"
else
  git config --local  user.email "muralisc@gmail.com"
  git config --local credential.username 'i330301'
fi

