directory: ~/Songs/
format_item: $artist - $composer - $album - $title - $genre - $year - $lyricist - $path
library: /var/tmp/musiclibrary.blb
import:
    copy: no
    write: yes
    autotag: no
plugins: edit info smartplaylist fromfilename play mpdadd ydl mpdstats
lastfm:
    user: muralisc
smartplaylist:
    playlist_dir: ~/.mpd/playlists
    playlists:
        - name: all.m3u
          query: 'last_played:..2016-04-17'
        - name: Hindi.m3u
          query: 'path::Hindi last_played:..2016-04-17'
        - name: English.m3u
          query: 'path::English last_played:..2016-04-17'
edit:
    itemfields: track title artist album lyrics path
lyrics:
    auto: yes
play:
  command: mpv

paths:
    # default: $albumartist/$album%aunique{}/$track $title
    default: $title
mpd:
    host: localhost
    port: 6600
ui:
  color: yes
