#! /bin/sh

# Reffer: https://git.sr.ht/~jbauer/dotfiles
pgrep -x sxhkd > /dev/null || sxhkd -r /tmp/sxhkd.log -c ~/.config/sxhkd/sxhkdrc ~/.config/sxhkd/sxhkdrc.common &
pgrep -x dunst > /dev/null || dunst &
pgrep -x polybar > /dev/null || polybar --reload example &

bspc monitor -d 1Kitty 2Fx 3obs/klive 4 5 6 7 8 9 10

bspc config border_width         0
bspc config window_gap           0
bspc config top_padding          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mpv state=floating
bspc rule -a Onboard state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
